apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mydiary-front
  name: mydiary-front
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mydiary-front
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/3tier-rolling-fe-be: "true"
        io.kompose.service: mydiary-front
    spec:
      containers:
        - image: henryk92/my-diary-front:1.0
          name: mydiary-front
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
