apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mydiary-back
  name: mydiary-back
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: mydiary-back
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: mydiary-back
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: user
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mydiary-db:3306/paperdb?serverTimezone=Asia/Seoul
            - name: SPRING_DATASOURCE_USERNAME
              value: user
          image: henryk92/my-diary-back:1.1
          name: mydiary-back
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
