apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mydiary-db
  name: mydiary-db
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: mydiary-db
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: mydiary-db
    spec:
      containers:
        - args:
            - --character-set-server=utf8
            - --collation-server=utf8_general_ci
          env:
            - name: MYSQL_DATABASE
              value: paperdb
            - name: MYSQL_PASSWORD
              value: user
            - name: MYSQL_ROOT_HOST
              value: '%'
            - name: MYSQL_ROOT_PASSWORD
              value: pass123
            - name: MYSQL_USER
              value: user
          image: mysql:5.7-debian
          name: mydiary-db
          ports:
            - containerPort: 3306
              hostPort: 13306
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
