apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mydiary-back
  name: mydiary-back
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mydiary-back
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: mydiary-back
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: user
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mydiary-db:3306/paperdb?serverTimezone=Asia/Seoul
            - name: SPRING_DATASOURCE_USERNAME
              value: user
          image: henryk/my-diary-back:1.0
          name: rolling-server
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
